# Generated by Django 3.2 on 2021-05-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_userfeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
